# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics calendar second
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repositories and diff history
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.second.svg
          token: ${{ secrets.METRICS_TOKEN_SECOND }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
